import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import StoreProvider from './StoreProvider';
import FacebookMsg from '@/components/FacebookMsg';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'IC Markets Partner ',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className} suppressHydrationWarning={true}>
				<StoreProvider>{children}</StoreProvider>
				<ToastContainer />
				{process.env.NODE_ENV === 'production' && <FacebookMsg />}
			</body>
		</html>
	);
}
